baseurl = "https://rjuro.com/unistra-nlp2024"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[languages]
  [languages.en]
    title = "UNISTRA NLP/LLM 2024"
    subtitle = "Natural Language Processing and Large Language Models - Roman Jurowetzki"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Next"
    newerPosts = "Back"
    olderPosts = "More"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "UNISTRA NLP/LLM"
      logoHomeLink = "https://rjuro.com/unistra-nlp2024"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
    [[languages.en.menu.main]]
      identifier = "reqs"
      name = "Reqs"
      url = "/reqs"
